# language
language: python
# python versions to be tested
python:
  - "3.5"
  - "3.6"
  - "3.7"
# branches to be tested
branches:
  only:
    - master
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# run tests, static code analysis and code coverage analysis
script:
  - python -m pytest
  - flake8 --statistics
  - pylint ajpoc
  - python -m pytest --cov=ajpoc
# push code coverage report to coveralls and codecov
after_success:
  - codecov
